### ISSUE TITLE
No file uploaded on OSX, windows

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/cppzmq-feedstock#1]
No files were uploaded to anaconda on os x and windows, probably due to the issue with the spyder recipe.

**Comment by SylvainCorlay** [comment]
^@jakirkham is there a means to force the initial upload to anaconda?

**Comment by ocefpaf** [comment]
You don't need to force anything. Just wait for Travis-CI to finish. See https://travis-ci.org/conda-forge/cppzmq-feedstock/builds/195860495

**Comment by SylvainCorlay** [comment]
The windows build is finished and nothing was pushed.

**Comment by ocefpaf** [comment]
The log says:

```
upload_or_check_non_existence .\recipe conda-forge --channel=main
Using Anaconda API: https://api.anaconda.org
No upload to take place - this configuration was skipped in build/skip.
Build success
```

I see you are skipping `win and py27` and only `py27` is in the matrix. See https://github.com/conda-forge/cppzmq-feedstock/blob/master/appveyor.yml#L16

**Comment by SylvainCorlay** [comment]
The original PR has all the python versions https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.10826

Did the rendering and the feedstock fail?

**Comment by ocefpaf** [comment]
> The original PR has all the python versions https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.10826

Staged recipes behave different because it needs to catch all possibilities.

> Did the rendering and the feedstock fail?

No. The recipe is flawed. See http://conda-forge.github.io/docs/buildwin.html#vc-features to fix it.

**Comment by SylvainCorlay** [comment]
It seems overkill to do that. It is header only (plus the cmake config files being installed). The only reason why I skip `windows + python 2.7` is that the zeromq dependecy is not packaged for that combination.

**Comment by ocefpaf** [comment]
> It seems overkill to do that. 

You still need to build at least one Python. BTW, if there is an overkill, it is in staged-recipes and not in the docs as you can control what you need.

Note that, since you are skipping the `default` python used in the matrix, you either have to play with the skip statement, like I said above, or change the `default`. The former is quick and depends only on you. But the latter may be a good idea in the long run. If you choose the latter then you need a PR targeting conda-smithy's templates.
